language: python

cache: pip

dist: trusty

python:
 - "3.6"

before_install:
  - pip install -U pip
  - chmod +x travis_setup.py
  - ./travis_setup.py

install:
  - pip install -e .
  
# try to build the package
script:
 - python setup.py install
