language: python

cache: pip

python:
 - "3.6"
 - "3.7"
 - "3.8"
 
before_install:
  - pip install -U pip
  - travis_setup.py

install:
  - pip install -e .
  
# try to build the package
script:
 - python setup.py install
